# Generated by Django 4.2 on 2023-05-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=100)),
                ('Description', models.TextField(default='Payment bill', verbose_name='Bill Description')),
                ('bill_type', models.CharField(choices=[('Course', 'Course'), ('Internet', 'Internet'), ('Marketing', 'Marketing'), ('Web Design', 'Web Design'), ('Video Design', 'Video Design'), ('Subscription', 'Subscription'), ('Consultation', 'Consultation'), ("AD's Campaign", "AD's Campaign"), ('Content writing', 'Content writing'), ('Digital product', 'Digital product'), ('Graphics Design', 'Graphics Design'), ('Thumbnail Design', 'Thumbnail Design'), ('Others', 'Others')], default='Web-design', max_length=50, verbose_name='Type of bill')),
                ('currency', models.CharField(choices=[('NGN', 'NGN')], default='NGN', max_length=50, verbose_name='Currency')),
                ('paid_by', models.CharField(default='No One', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
