# Generated by Django 4.2 on 2023-05-03 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=100)),
                ('Description', models.TextField(default='Payment bill', verbose_name='Bill Description')),
                ('bill_type', models.CharField(choices=[('Web Design Bill', 'Web Design Bill'), ('Graphics Design Bill', 'Graphics Design Bill'), ('Thumbnail Design Bill', 'Thumbnail Design Bill'), ('Video Design Bill', 'Video Design Bill'), ('Content writing Bill', 'Content writing Bill'), ('Marketing Bill', 'Marketing Bill'), ("AD's Campaign Bill", "AD's Campaign Bill"), ('Subscription Bill', 'Subscription Bill'), ('Course Bill', 'Course Bill'), ("NFT's sales Bill", "NFT's sales Bill"), ('Digital product Bill', 'Digital product Bill'), ('Internet Bill', 'Internet Bill'), ('Consultation Bill', 'Consultation Bill'), ('Others Bill', 'Others')], default='Web-design', max_length=50, verbose_name='Type of bill')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWD', 'ZWD'), ('NGN', 'NGN')], default='NGN', max_length=50, verbose_name='Currency')),
                ('paid_by', models.CharField(default='No One', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
