# Generated by Django 4.2 on 2023-05-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages_pic')),
                ('goal_amount', models.FloatField(default=0)),
                ('current_amount', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('message', models.CharField(default='Thank you for your donation', max_length=50)),
                ('donation_type', models.CharField(choices=[('Support', 'Support'), ('Funding', 'Funding'), ('Charity', 'Charity'), ('Donations', 'Donations'), ('Financing', 'Financing'), ('Appreciation', 'Appreciation'), ('Contributions', 'Contributions')], default='Support', max_length=20, verbose_name='Donation category')),
                ('currency', models.CharField(choices=[('NGN', 'NGN')], default='NGN', max_length=50, verbose_name='Currency')),
                ('public', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaigns.campaign')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
